FROM yovio/crontab:alpine
MAINTAINER yovio@hotmail.com

RUN set -ex \
# install python3
    && apk add --no-cache \
    python3 \
# making logging pipe
    && ln -s /usr/bin/python3 /usr/bin/python \
	&& /usr/bin/easy_install-3.6 pip
	
	
COPY start-cron /usr/sbin

CMD ["start-cron"]