FROM yovio/crontab:alpine
MAINTAINER yovio@hotmail.com

# install python3
RUN apk add --no-cache python3 \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && /usr/bin/easy_install-3.6 pip

CMD ["start-cron"]
